 spring:
   datasource:
     url: jdbc:mysql://localhost:3306/department_db
     username: root
     password: Thuytiencute22

   jpa:
     properties:
       hibernate:
         dialect: org.hibernate.dialect.MySQL8Dialect
     hibernate:
       ddl-auto: update
